version: '3.1'
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      postgres: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5678:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
  stock:
    image: sd-stock-service:latest
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      DB_POSTGRES_HOST: host.docker.internal